// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE2T3tcH2o0Yb6MT2NzsgPvR8WehCIRS4',
    appId: '1:107866395626:web:c917ff36e22687f05a9893',
    messagingSenderId: '107866395626',
    projectId: 'podo-e49b2',
    authDomain: 'podo-e49b2.firebaseapp.com',
    storageBucket: 'podo-e49b2.appspot.com',
    measurementId: 'G-SMW734Q34J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZpVvsXgXKCXeP-dDL-KWjt0RzD8Buvec',
    appId: '1:107866395626:android:73cdd8bf960c1c7b5a9893',
    messagingSenderId: '107866395626',
    projectId: 'podo-e49b2',
    storageBucket: 'podo-e49b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsqAX8QDjEjmgd4X1-n89ewCwcH616Pyc',
    appId: '1:107866395626:ios:da7cf5804378ce4f5a9893',
    messagingSenderId: '107866395626',
    projectId: 'podo-e49b2',
    storageBucket: 'podo-e49b2.appspot.com',
    iosClientId: '107866395626-9ktc8e3slvmn4fl6sij5n1hb61blkij9.apps.googleusercontent.com',
    iosBundleId: 'com.example.podoAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsqAX8QDjEjmgd4X1-n89ewCwcH616Pyc',
    appId: '1:107866395626:ios:da7cf5804378ce4f5a9893',
    messagingSenderId: '107866395626',
    projectId: 'podo-e49b2',
    storageBucket: 'podo-e49b2.appspot.com',
    iosClientId: '107866395626-9ktc8e3slvmn4fl6sij5n1hb61blkij9.apps.googleusercontent.com',
    iosBundleId: 'com.example.podoAdmin',
  );
}
